/* calibrate_best_b.c — Direct empirical measurement of the real fastest
 * hybrid-engine block size B(n,k), replacing select_best_B()'s summed-
 * analytical-constants prediction with a small, per-device empirical
 * lookup table -- same methodology and rationale as
 * tools/calibrate_crossover.c (LAPACK ILAENV precedent: measure the real
 * decision directly rather than summing calibrated constants, which was
 * found fragile in aggregate even with every individual constant
 * validated, both for the linear-vs-hybrid crossover AND for B
 * selection -- see tools/validate_best_b.c's confirmation that
 * select_best_B() is measurably wrong by 7-11% on M3 Pro and 2-9% on
 * Zen4, same systematic direction: overestimating the benefit of larger
 * B).
 *
 * Unlike the crossover table (a continuous threshold, log-linearly
 * interpolated), B is a discrete/categorical choice among {8,16,24,32,
 * 48,64} -- there is no meaningful "interpolation" between B=32 and
 * B=64. Lookup is nearest-neighbor over a 2D (n,k) grid instead.
 *
 * For each (n,k) grid point read from a point-list CSV (columns n,k,
 * generated by tools/gen_calib_skeleton.py), this tool times the REAL
 * hybrid engine at every candidate B using a 1-rep ranking pass followed
 * by a 2-rep runoff only on the top-2 candidates if they are within ~3%
 * of each other — much faster than median-of-7 on every candidate while
 * retaining decision quality where it matters.
 *
 * Usage:
 *   calibrate_best_b <input_csv> -o <output_csv> [--narrow-around B1,B2,...]
 *
 *   input_csv:  point-list CSV with header "n,k" (from gen_calib_skeleton.py)
 *   output_csv: where to write results (n,k,best_B). Resumable: skips (n,k)
 *               already present in an existing partial output.
 *   --narrow-around: only test the listed B values plus their immediate
 *                    neighbors in {8,16,24,32,48,64}. For single-point
 *                    refinement additions where a full sweep is unnecessary.
 *
 * Conventions (match bench_grid crossover and calibrate_crossover exactly):
 *   Q=256, srand(42), payout[m] = n-m, S[i] = 100+9900*rand()/RAND_MAX
 *
 * Build (macOS M3 Pro):
 *   gcc -O3 -march=native -Isrc -Idevices/m3_pro -I/opt/homebrew/include \
 *       -o build/calibrate_best_b tools/calibrate_best_b.c src/icm.c \
 *       -L/opt/homebrew/lib -lfftw3 -lm -framework Accelerate
 * Build (Linux/Zen4, AOCL-FFTW):
 *   gcc -O3 -march=znver4 -Isrc -Idevices/zen4 -I/usr/local/aocl-fftw/include \
 *       -o build/calibrate_best_b tools/calibrate_best_b.c src/icm.c \
 *       -L/usr/local/aocl-fftw/lib -Wl,-rpath,/usr/local/aocl-fftw/lib \
 *       -lfftw3 -lm -ldl -lmvec
 */
#include "icm.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#define Q_PROBE        256
#define N_CANDIDATES   6
#define TOP_RUNOFF_N   2
#define RUNOFF_PCT     3.0   /* top-2 within this % get extra reps */

static const int B_candidates[N_CANDIDATES] = {8, 16, 24, 32, 48, 64};

static int cmp_double(const void *a, const void *b) {
    double da = *(const double *)a, db = *(const double *)b;
    return (da > db) ? 1 : (da < db) ? -1 : 0;
}

/* ── Narrow-around: parse comma-separated B values ──────────────── */

static int parse_narrow_Bs(const char *arg, int *out_Bs, int max_out) {
    /* Parse "B1,B2,..." into out_Bs. Returns count. */
    char *buf = strdup(arg);
    if (!buf) { fprintf(stderr, "OOM parsing --narrow-around\n"); exit(1); }
    int count = 0;
    char *save = NULL;
    char *tok = strtok_r(buf, ",", &save);
    while (tok && count < max_out) {
        out_Bs[count++] = atoi(tok);
        tok = strtok_r(NULL, ",", &save);
    }
    free(buf);
    return count;
}

static int B_in_narrow_set(int B, const int *narrow_Bs, int narrow_n) {
    /* Test B itself, plus its immediate neighbours in the candidate list. */
    for (int i = 0; i < narrow_n; i++) {
        int target = narrow_Bs[i];
        if (B == target) return 1;
        /* Find target's index in B_candidates, then allow neighbours */
        for (int j = 0; j < N_CANDIDATES; j++) {
            if (B_candidates[j] == target) {
                if (j > 0 && B == B_candidates[j-1]) return 1;
                if (j < N_CANDIDATES-1 && B == B_candidates[j+1]) return 1;
                break;
            }
        }
    }
    return 0;
}

/* ── Single-rep timing (no median) ──────────────────────────────── */

static double time_hybrid_B_one(int n, int k, int B, const double *S,
                                const double *payout, double *equity) {
    void *hc = icm_hybrid_ctx_create(n, S, k, B);
    double t = icm_run_engine(n, S, Q_PROBE, payout, k, equity,
                               icm_engine_hybrid(), hc) / (double)Q_PROBE;
    /* Deliberately no icm_ctx_destroy(): this is a short-lived
     * calibration program, and getting the EngineKind enum wrong
     * would cause a segfault. Leaking memory in a one-shot offline
     * tool is safe; guessing the enum wrong isn't. */
    return t;
}

/* ── Resumability: read existing output, build set of done (n,k) ─── */

typedef struct {
    int n, k;
} Point;

static Point *done_points = NULL;
static int   done_count   = 0;
static int   done_cap     = 0;

static void load_done(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return;  /* no existing output — fine, start fresh */
    char line[256];
    int first = 1;
    while (fgets(line, sizeof(line), f)) {
        /* Skip comment/header lines */
        if (line[0] == '#') continue;
        if (first) { first = 0; continue; }  /* skip header "n,k,best_B" */
        int n, k, dummy_B;
        if (sscanf(line, "%d,%d,%d", &n, &k, &dummy_B) == 3) {
            if (done_count >= done_cap) {
                done_cap = done_cap ? done_cap * 2 : 64;
                done_points = (Point *)realloc(done_points,
                                               done_cap * sizeof(Point));
                if (!done_points) { fprintf(stderr, "OOM\n"); exit(1); }
            }
            done_points[done_count].n = n;
            done_points[done_count].k = k;
            done_count++;
        }
    }
    fclose(f);
    fprintf(stderr, "[resume] %d (n,k) points already in %s — will skip\n",
            done_count, path);
}

static int is_done(int n, int k) {
    for (int i = 0; i < done_count; i++) {
        if (done_points[i].n == n && done_points[i].k == k) return 1;
    }
    return 0;
}

/* ── Main ───────────────────────────────────────────────────────── */

int main(int argc, char **argv) {
    const char *input_csv  = NULL;
    const char *output_csv = NULL;
    int narrow_Bs[16];
    int narrow_n = 0;
    int use_narrow = 0;

    /* Parse args */
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "-o")) {
            if (i + 1 < argc) output_csv = argv[++i];
            else { fprintf(stderr, "-o requires a path\n"); return 1; }
        } else if (!strcmp(argv[i], "--narrow-around")) {
            if (i + 1 < argc) {
                narrow_n = parse_narrow_Bs(argv[++i], narrow_Bs, 16);
                use_narrow = 1;
            } else { fprintf(stderr, "--narrow-around requires B1,B2,...\n"); return 1; }
        } else if (argv[i][0] != '-') {
            input_csv = argv[i];
        } else {
            fprintf(stderr, "Unknown flag: %s\n", argv[i]);
            return 1;
        }
    }

    if (!input_csv) {
        fprintf(stderr,
                "Usage: calibrate_best_b <input_csv> -o <output_csv> "
                "[--narrow-around B1,B2,...]\n");
        return 1;
    }
    if (!output_csv) {
        fprintf(stderr, "Error: -o <output_csv> required\n");
        return 1;
    }

    /* ── Resumability ─────────────────────────────────────────── */
    load_done(output_csv);

    /* ── Open output (append mode) ────────────────────────────── */
    FILE *out = fopen(output_csv, "a");
    if (!out) {
        fprintf(stderr, "Cannot open output %s: %s\n", output_csv, strerror(errno));
        return 1;
    }
    /* If starting fresh, write header */
    if (done_count == 0) {
        fprintf(out, "# Direct empirical best-B measurement (1-rep rank + top-2 runoff)\n");
        fprintf(out, "# narrow-around: %s\n", use_narrow ? "yes" : "no (full sweep)");
        fprintf(out, "n,k,best_B\n");
    }

    /* ── Init ICM ─────────────────────────────────────────────── */
    icm_init(NULL);

    /* ── Read input CSV ───────────────────────────────────────── */
    FILE *in = fopen(input_csv, "r");
    if (!in) {
        fprintf(stderr, "Cannot open input %s: %s\n", input_csv, strerror(errno));
        return 1;
    }

    char line[256];
    int line_no = 0;
    int skipped = 0, processed = 0;

    while (fgets(line, sizeof(line), in)) {
        line_no++;
        /* Skip comments and header */
        if (line[0] == '#') continue;
        if (line_no == 1 && strncmp(line, "n,k", 3) == 0) continue;

        int n, k;
        if (sscanf(line, "%d,%d", &n, &k) != 2) {
            /* maybe trailing newline, empty, etc. */
            if (line[0] == '\n' || line[0] == '\0') continue;
            fprintf(stderr, "Warning: skipping malformed line %d: %s", line_no, line);
            continue;
        }

        if (k > n) continue;  /* invalid */

        if (is_done(n, k)) { skipped++; continue; }

        /* ── Allocate per-point arrays ──────────────────────── */
        double *S      = (double *)malloc(n * sizeof(double));
        double *payout = (double *)malloc(k * sizeof(double));
        double *equity = (double *)malloc(n * sizeof(double));
        if (!S || !payout || !equity) { fprintf(stderr, "OOM\n"); return 1; }

        /* Generate stacks: same convention as every other tool in this project */
        srand(42);
        for (int i = 0; i < n; i++)
            S[i] = 100.0 + 9900.0 * ((double)rand() / RAND_MAX);

        /* payout[m] = (n-m) — matches bench_grid crossover */
        for (int m = 0; m < k; m++)
            payout[m] = (double)(n - m);

        /* ── Phase 1: 1 rep per candidate to rank ──────────── */
        double t1[N_CANDIDATES];
        int    valid[N_CANDIDATES];
        int    n_valid = 0;

        for (int bi = 0; bi < N_CANDIDATES; bi++) {
            int B = B_candidates[bi];
            if (B > n) { valid[bi] = 0; continue; }
            if (use_narrow && !B_in_narrow_set(B, narrow_Bs, narrow_n))
                { valid[bi] = 0; continue; }
            valid[bi] = 1;
            n_valid++;
            t1[bi] = time_hybrid_B_one(n, k, B, S, payout, equity);
        }

        if (n_valid == 0) {
            fprintf(stderr, "n=%d k=%d: no valid B candidates\n", n, k);
            free(S); free(payout); free(equity);
            continue;
        }

        /* ── Phase 2: find top-2 by 1-rep time ─────────────── */
        int    best_idx  = -1, second_idx = -1;
        double best_t    = 1e18, second_t = 1e18;

        for (int bi = 0; bi < N_CANDIDATES; bi++) {
            if (!valid[bi]) continue;
            if (t1[bi] < best_t) {
                second_t   = best_t;
                second_idx = best_idx;
                best_t     = t1[bi];
                best_idx   = bi;
            } else if (t1[bi] < second_t) {
                second_t   = t1[bi];
                second_idx = bi;
            }
        }

        int    best_B_final;
        double best_time_final;

        /* ── Phase 3: runoff only if top-2 within RUNOFF_PCT ── */
        int need_runoff = 0;
        if (second_idx >= 0 && best_idx >= 0 && best_t > 0.0) {
            double pct_diff = 100.0 * (second_t - best_t) / best_t;
            if (pct_diff <= RUNOFF_PCT)
                need_runoff = 1;
        }

        if (need_runoff) {
            /* 2 more reps on each of the top-2, then median of 3 */
            double a_samples[3], b_samples[3];
            a_samples[0] = t1[best_idx];
            b_samples[0] = t1[second_idx];

            for (int r = 1; r < 3; r++) {
                a_samples[r] = time_hybrid_B_one(n, k, B_candidates[best_idx],
                                                  S, payout, equity);
                b_samples[r] = time_hybrid_B_one(n, k, B_candidates[second_idx],
                                                  S, payout, equity);
            }
            qsort(a_samples, 3, sizeof(double), cmp_double);
            qsort(b_samples, 3, sizeof(double), cmp_double);

            double med_a = a_samples[1];  /* median of 3 */
            double med_b = b_samples[1];

            if (med_a <= med_b) {
                best_B_final    = B_candidates[best_idx];
                best_time_final = med_a;
            } else {
                best_B_final    = B_candidates[second_idx];
                best_time_final = med_b;
            }
        } else {
            /* No runoff — the 1-rep winner stands */
            best_B_final    = B_candidates[best_idx];
            best_time_final = t1[best_idx];
        }

        /* ── Emit ──────────────────────────────────────────── */
        fprintf(out, "%d,%d,%d\n", n, k, best_B_final);
        fflush(out);
        fprintf(stderr, "n=%d k=%d -> best_B=%d (%.0f ns/qp)%s\n",
                n, k, best_B_final, best_time_final,
                need_runoff ? " [runoff]" : "");
        processed++;

        free(S); free(payout); free(equity);
    }

    fclose(in);
    fclose(out);
    free(done_points);

    fprintf(stderr, "Done: %d processed, %d skipped (already done)\n",
            processed, skipped);
    return 0;
}
